#!/bin/bash
	if [ -e /usr/sbin/edithosts ] ; then

echo "edithosts:Already installed"

	else

echo "edithosts:Installing..."

## backup /etc/hosts
cd edithosts
sudo mkdir /etc/hosts.d/ -m 644
echo "edithosts:Backup /etc/hosts"
sudo cp /etc/hosts /etc/hosts.d/hosts.bak
sudo sed -i '1i## Do not edit this file directly, but only through the command: edithosts' /etc/hosts
sudo cp /etc/hosts /etc/hosts.d/hosts.conf

## installing in to /opt/edithosts
sudo mkdir /opt/edithosts/
sudo cp autoupdate.sh /opt/edithosts/autoupdate.sh
sudo cp update.sh /opt/edithosts/update.sh
sudo cp install.sh /opt/edithosts/install.sh
sudo cp version /opt/edithosts/version
sudo cp edithosts.sh /opt/edithosts/edithosts.sh && sudo ln -s /opt/edithosts/edithosts.sh /usr/sbin/edithosts
sudo cp gethosts.sh /opt/edithosts/gethosts.sh && sudo ln -s /opt/edithosts/gethosts.sh /usr/sbin/gethosts
sudo cp cron.weekly-edithosts /opt/edithosts/
sudo cp uninstall.sh /opt/edithosts/uninstall.sh
sudo cp licence /opt/edithosts/licence
sudo cp temporarilydisableblocking.sh /opt/edithosts/temporarilydisableblocking.sh && sudo ln -s /opt/edithosts/temporarilydisableblocking.sh /usr/sbin/temporarilydisableblocking
sudo cp refreshblocking.sh /opt/edithosts/refreshblocking.sh && sudo ln -s /opt/edithosts/refreshblocking.sh /usr/sbin/refreshblocking
sudo gzip -c man/cs/man1/edithosts.1 > man/cs/man1/edithosts.1.gz
sudo cp man/cs/man1/edithosts.1.gz /usr/share/man/cs/man1/edithosts.1.gz
sudo chmod 755 /opt/edithosts -R

## periodic updates
sudo cp /opt/edithosts/autoupdate.sh /etc/cron.monthly/updateprogramuedithosts
sudo cp /opt/edithosts/cron.weekly-edithosts /etc/cron.weekly/edithosts

echo "edithosts:Installing OK, Do not edit /etc/hosts file directly, but only through the command: edithosts."
echo -e "edithosts:To uninstall a rollback, use the command:\n/opt/edithosts/uninstall.sh"

sudo /opt/edithosts/gethosts.sh

	fi
exit 0
